<?php
$films = [
    [
        "name" => "Пірати Карибського моря. Прокляття Чорної перлини",
        "genre" => "бойовик, комедія, пригоди",
        "director" => "Гор Вербінскі",
        "year" => 2003,
        "rating" => 9.3,
        "studio" => "Walt Disney Pictures",
        "sessions" => "10:00; 18:00",
        "price" => "120",
        //"sits" => "30",
    ],
    [
        "name" => "Титанік",
        "genre" => "драма, історичний фільм",
        "director" => "Джеймс Камерон",
        "year" => 1997,
        "rating" => 9.1,
        "studio" => "20th Century Fox",
        "sessions" => "10:00; 20:10",
        "price" => "130",
        //"sits" => "50",
    ],
    [
        "name" => "Володар перснів: Хранителі персня",
        "genre" => "фентезі, пригоди",
        "director" => "Пітер Джексон",
        "year" => 2001,
        "rating" => 8.8,
        "studio" => "Warner Bros. Pictures, New Line Cinema",
        "sessions" => "16:00; 19:00",
        "price" => "100",
        //"sits" => "35",
    ],
    [
        "name" => "Гаррі Поттер і філософський камінь",
        "genre" => "фентезі",
        "director" => "Кріс Коламбус",
        "year" => 2001,
        "rating" => 8.9,
        "studio" => "Warner Bros. Pictures",
        "sessions" =>  "11:30; 14:00",
        "price" => "150",
        //"sits" => "30",
    ],
    [
        "name" => "Інтерстеллар",
        "genre" => "наукова фантастика",
        "director" => "Крістофер Нолан",
        "year" => 2014,
        "rating" => 8.8,
        "studio" => "Paramount Pictures",
        "sessions" =>  "11:00; 19:30",
        "price" => "140",
        //"sits" => "40",
    ],
    [
        "name" => "Назад у майбутнє",
        "genre" => "фантастика, комедія, пригоди",
        "director" => "Роберт Земекіс",
        "year" => 1985,
        "rating" => 8.6,
        "studio" => "Universal Pictures",
        "sessions" =>  "15:45; 20:00, 21:00",
        "price" => "110",
        //"sits" => "40",
    ],
    
    
];

$users = [
    'admin' => ['pass' => 'qwerty', 'role' => 'admin'],
    'james' => ['pass' => 'j88s', 'role' => 'admin'],
    'mary' => ['pass' => 'ffff', 'role' => 'user'],
    'i_am_admin' => ['pass' => '12345678', 'role' => 'admin'],
    'user' => ['pass' => 'userrr', 'role' => 'user'],
    'alex' => ['pass' => 'al123', 'role' => 'user'],
];